### ISSUE TITLE
[BUG]: Issue with Entering Zip Code

### ISSUE THREAD

**Issue by surapuramakhil** [feder-cr/Jobs_Applier_AI_Agent_AIHawk#601]
### Describe the bug

LLM output says zip code not provided but config do contain zip code information

<img width="1512" alt="Screenshot 2024-10-25 at 11 30 50 AM" src="https://github.com/user-attachments/assets/727363df-ad72-4350-a428-b21925a707a6">

```sh
2024-10-25 11:30:54.077 | DEBUG    | src.aihawk_easy_applier:_check_for_errors:322 - Checking for form errors
2024-10-25 11:30:54.090 | ERROR    | src.aihawk_easy_applier:_check_for_errors:325 - Form submission failed with errors: [<selenium.webdriver.remote.webelement.WebElement (session="c7a10f22b1272f97dde7baec9bf8f763", element="f.3EAFABD5050C9DE8487CB56B054174C8.d.5E9D1E085250003EA43531DC38393606.e.17174")>]
2024-10-25 11:30:54.101 | ERROR    | src.aihawk_easy_applier:job_apply:151 - Failed to apply to job: Job(title='Back End Engineer', company='Cogility Software', location='Irvine, CA (Remote)', link='https://www.linkedin.com/jobs/view/4058728835/', apply_method='Easy Apply', description="About the job\nWhat You Will Do\n\nCogility Software is looking for an experienced Back End Engineer who wants to make an impact not only in the office, but in the world around them. We need talented developers to help shape the future of our products. Expect to find great meaning in what you do, enjoy it, and be compensated competitively for your time and talents.\n\nArchitect interfaces for customer use, focusing on solving complex problems\nDesign and build capabilities to enable users to visualize and interact with data for analytical purposes\nEngage in all stages of the product development and deployment lifecycle, including idea generation, user interviews, planning, design, prototyping, execution, shipping, and iteration\nCollaborate with cross-functional teams to deliver high-quality solutions\nContribute to the planning and execution of backend development tasks\nImplement and maintain backend functionalities to support user-facing features\nCollaborate with Front End Engineers and other team members to achieve seamless integration between frontend and backend components\nParticipate in code reviews and provide constructive feedback to maintain code quality standards\n\nWhat You Bring To The Table\n\nMust have a minimum of 4+ years of work experience in a similar position or product development\nRequires a Bachelor’s degree or technical certification or equivalent work experience\nAbility to write clean, maintainable code\nFamiliarity with data structures, storage systems, cloud infrastructure, front-end frameworks, and other technical tools\nExperience working with Phoenix & Elixir on the backend, but proficiency inRuby, Clojure, or GO will also be considered\nLooking for experience in these areas:Redis,Postgres, Kubernetes, Kafka, and Elasticsearch\nReal time data processing (bonus)\nProficient experience using server APIs (GraphQL, REST etc)\nA good understanding of the software development process including development and deployment\nUnderstanding and implementation of security and data protection\nEligibility for a TS/SCI security clearance\n\nWHAT WE BRING TO THE TABLE\n\nSalary Range: $110K - $130K\nCompany Equity\n401k safe harbor match\nGenerous medical, dental, vision plans, and FSA\nVacation, sick, and paid holidays offered\nJob training, conferences, and time allotted for learning\nPromote from within\nDaily sync\nCasual environment\nWork with talented and collaborative co-workers\nStand/ sit workstations & a game room\nKitchen stocked with snacks and drinks\n\nTECHNOLOGIES WE USE\n\nHosting: AWS Cloud and AWS services (Server and Serverless)\nBackend: Elixir, NodeJS, Java, GraphQL, Postgres, and Redis\nFrontend: Typescript and React\nSearch and analytics: OpenSearch andKafka\nIndustry-standard build tooling and CI/CD: CodePipeline and GitHub\nMonitoring and Logging: Prometheus andGrafana\nCode Quality: SonarQube andPlaywright\nProject Management: Jira\nContainerization and Orchestration: Docker and Kubernetes\nInfrastructure deployment and automation: Terraform, CloudFormation, and Ansible\n\nAbout The Company\n\nCogility is a leading provider of continuous intelligence software solutions that deliver efficient, rapid, and impactful decision support automation for government and commercial organizations - enabling our customers to expedite opportunity or get left of harm.\n\nA highly scalable AI/ML peer technology, Cogility's Cogynt platform, offers unified, hierarchical Complex Event Processing that allows analysts to efficiently process massive, diverse, and complex signals of structured and unstructured data leveraging dynamic, no-code pattern modeling, and behavioral analytics to gain high-confidence, actionable decision results at machine speed with full determination traceability. This patented approach employs the capabilities of Apache Flink and Kafka wrapped in an extensible, enterprise-grade platform.\n\nAbout The Products\n\nThe company currently has two distinguished solutions developed on its Cogynt platform. Cogility’s Continuous Insider Threat Intelligence solution allows government agencies to efficiently take a holistic-person approach to detect and respond to unwanted insider threat behavior based on technical and social indicators of risk in a single pane of glass. Cogility's TacitRed is a turnkey, SaaS solution that provides Active Attack Surface Intelligence – offering on-demand, curated threat intelligence that empowers security analysts to readily see and assess their and their business associates security risks and take immediate and decisive actions to mitigate impactful cyber exposures.\n\nCogility recruits, employs, trains, compensates, and promotes regardless of race, religion, color, national origin, sex, disability, age, veteran status, and other protected status as required by applicable law.\n\nPowered by JazzHR\n\ntDV5tANvSN", summarize_job_description='# Job Description Summary\n\n## Technical Skills\n- Proficiency in backend programming languages: Elixir (preferred), Ruby, Clojure, or Go.\n- Experience with backend frameworks and tools: Phoenix, NodeJS, Java, GraphQL, Postgres, Redis.\n- Familiarity with data structures, storage systems, and cloud infrastructure (AWS).\n- Knowledge of real-time data processing (bonus).\n- Experience with server APIs (GraphQL, REST).\n- Understanding of security and data protection practices.\n- Familiarity with containerization and orchestration tools: Docker, Kubernetes.\n- Experience with CI/CD tools and practices: CodePipeline, GitHub.\n- Knowledge of monitoring and logging tools: Prometheus, Grafana.\n- Familiarity with project management tools: Jira.\n- Experience with infrastructure deployment and automation tools: Terraform, CloudFormation, Ansible.\n\n## Soft Skills\n- Strong problem-solving abilities.\n- Excellent communication skills for collaboration with cross-functional teams.\n- Ability to engage in all stages of the product development lifecycle.\n- Capacity to provide constructive feedback during code reviews.\n- Strong time management skills to handle multiple tasks and deadlines.\n- Adaptability to work in a casual yet collaborative environment.\n\n## Educational Qualifications and Certifications\n- Bachelor’s degree in Computer Science, Software Engineering, or a related field, or equivalent technical certification or work experience.\n\n## Professional Experience\n- Minimum of 4+ years of work experience in backend development or product development.\n- Experience in developing and deploying backend functionalities that support user-facing features.\n- Familiarity with the software development process, including planning, design, and execution.\n\n## Role Evolution\n- The role is expected to evolve with advancements in cloud technologies and the increasing importance of data security and real-time analytics.\n- Future trends may require deeper expertise in AI/ML technologies as the company focuses on complex event processing and decision support automation.\n- The demand for agile methodologies and continuous integration/deployment practices will likely increase, necessitating ongoing learning and adaptation to new tools and frameworks.\n- As remote work becomes more prevalent, skills in virtual collaboration and communication will be increasingly important. \n\nThis overview provides a comprehensive guide for identifying qualified candidates for the Back End Engineer position at Cogility Software.', pdf_path='', recruiter_link=''), error: Traceback (most recent call last):
  File "/Users/akhilsurapuram/openSource/linkedIn_auto_jobs_applier_with_AI/src/aihawk_easy_applier.py", line 145, in job_apply
    self._fill_application_form(job)
  File "/Users/akhilsurapuram/openSource/linkedIn_auto_jobs_applier_with_AI/src/aihawk_easy_applier.py", line 292, in _fill_application_form
    if self._next_or_submit():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akhilsurapuram/openSource/linkedIn_auto_jobs_applier_with_AI/src/aihawk_easy_applier.py", line 310, in _next_or_submit
    self._check_for_errors()
  File "/Users/akhilsurapuram/openSource/linkedIn_auto_jobs_applier_with_AI/src/aihawk_easy_applier.py", line 326, in _check_for_errors
    raise Exception(f"Failed answering or file upload. {str([e.text for e in error_elements])}")
Exception: Failed answering or file upload. ['Please enter a valid answer']

2024-10-25 11:30:54.102 | DEBUG    | src.aihawk_easy_applier:job_apply:153 - Discarding application due to failure
2024-10-25 11:30:54.102 | DEBUG    | src.aihawk_easy_applier:_discard_application:329 - Discarding application
2024-10-25 11:31:00.963 | ERROR    | src.aihawk_job_manager:apply_jobs:381 - Failed to apply for Back End Engineer at Cogility Software: Failed to apply to job! Original exception:
Traceback:
Traceback (most recent call last):
  File "/Users/akhilsurapuram/openSource/linkedIn_auto_jobs_applier_with_AI/src/aihawk_easy_applier.py", line 145, in job_apply
    self._fill_application_form(job)
  File "/Users/akhilsurapuram/openSource/linkedIn_auto_jobs_applier_with_AI/src/aihawk_easy_applier.py", line 292, in _fill_application_form
    if self._next_or_submit():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akhilsurapuram/openSource/linkedIn_auto_jobs_applier_with_AI/src/aihawk_easy_applier.py", line 310, in _next_or_submit
    self._check_for_errors()
  File "/Users/akhilsurapuram/openSource/linkedIn_auto_jobs_applier_with_AI/src/aihawk_easy_applier.py", line 326, in _check_for_errors
    raise Exception(f"Failed answering or file upload. {str([e.text for e in error_elements])}")
Exception: Failed answering or file upload. ['Please enter a valid answer']

2024-10-25 11:31:00.963 | DEBUG    | src.aihawk_job_manager:write_to_file:386 - Writing job application result to file: failed
2024-10-25 11:31:00.972 | DEBUG    | src.aihawk_job_manager:write_to_file:413 - Job data appended to existing file: failed
```

### Branch

None

**Comment by GeeGeeWP** [comment]
+1 this issue. When running the main.py function, I am getting an error for Zip Code: 
<img width="1787" alt="Screenshot 2024-10-25 at 12 44 29 PM" src="https://github.com/user-attachments/assets/d30249d6-2fa5-4dee-8410-3ed0dedf476a">

**Comment by FrancescoVassalli** [comment]
Does this happen on every app or only intermittently? Which models have you tried this with?

**Comment by surapuramakhil** [comment]
it happens most of the time. as the result that job get skipped.
